"use client";

import * as React from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, BarChart3, PieChart, Users } from "lucide-react";
import { cn } from "@/lib/cn";
import { formatPct, formatZAR } from "@/lib/format";

type Holding={symbol?:string;ticker?:string;shares?:number;quantity?:number;weight?:number};
type Strategy={id:string;name:string;short_name?:string;sector?:string;description?:string;holdings?:Holding[];benchmark_name?:string};
type ReturnRow={as_of_date:string;basket_value:number|null;ytd_pct:number|null;all_pct:number|null};
type Sec={symbol:string;name?:string;logo_url?:string;last_price?:number;change_percent?:number};
type Investor={userId:string;name:string;value:number;ytd:number|null};
type Detail={strategy:Strategy;returns:ReturnRow[];securities:Record<string,Sec>;investors:Investor[]};

export default function StrategyOverviewPage(){
  const {id}=useParams<{id:string}>(); const router=useRouter();
  const [data,setData]=React.useState<Detail|null>(null);
  React.useEffect(()=>{void fetch(`/api/admin/factsheets?action=detail&id=${encodeURIComponent(id)}`,{cache:"no-store"}).then(r=>r.json()).then(detail=>{if(detail.ok)setData(detail);});},[id]);
  if(!data)return <div className="py-24 text-center text-sm text-muted-foreground">Loading strategy workspace…</div>;
  const s=data.strategy, holdings=Array.isArray(s.holdings)?s.holdings:[], latest=data.returns.at(-1);
  const normalize=(value:string)=>value.replace(/\.JO$/i,"").toUpperCase();
  const sec=(h:Holding)=>data.securities[String(h.ticker||h.symbol||"")]||data.securities[`${normalize(String(h.ticker||h.symbol||""))}.JO`]||data.securities[normalize(String(h.ticker||h.symbol||""))];
  const minValue=holdings.reduce((sum,h)=>sum+Number(h.shares||h.quantity||1)*(Number(sec(h)?.last_price||0)/100),0);
  return <div className="mx-auto max-w-7xl space-y-4 pb-10">
    <SecurityRibbon holdings={holdings} securityFor={sec}/>
    <button type="button" onClick={()=>router.back()} className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5"/>Back to strategies</button>
    <header className="glass-panel flex flex-wrap items-start gap-4 p-4"><div className="min-w-0 flex-1"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-primary">Strategy overview</p><h1 className="mt-1 text-xl font-bold">{s.name}</h1><p className="text-xs text-muted-foreground">{s.short_name||"MINT"}{s.sector?` · ${s.sector}`:""}</p>{s.description&&<p className="mt-2 max-w-3xl text-xs leading-relaxed text-foreground/70">{s.description}</p>}</div><div className="grid grid-cols-4 divide-x divide-border overflow-hidden rounded-xl border border-border bg-background/30"><Kpi label="Min value" value={minValue?formatZAR(minValue):"—"}/><Kpi label="YTD" value={latest?.ytd_pct!=null?formatPct(Number(latest.ytd_pct)):"—"}/><Kpi label="Holdings" value={String(holdings.length)}/><Kpi label="Investors" value={String(data.investors.length)}/></div></header>
    <div className="grid grid-cols-12 gap-4">
      <section className="glass-panel col-span-12 p-4 lg:col-span-8"><CardTitle icon={BarChart3} title="Performance vs Benchmark"/><PerformanceChart rows={data.returns}/><div className="mt-2 flex justify-end gap-4 text-[9px] text-muted-foreground"><span><i className="mr-1 inline-block h-0.5 w-3 bg-primary"/>Strategy</span><span><i className="mr-1 inline-block h-0.5 w-3 bg-muted-foreground"/>JSE ALSI · benchmark history unavailable</span></div></section>
      <section className="glass-panel col-span-12 p-4 lg:col-span-4"><CardTitle icon={PieChart} title="Sector Exposure"/><ExposureDonut holdings={holdings}/></section>
      <section className="glass-panel col-span-12 overflow-hidden lg:col-span-7"><div className="border-b border-border px-4 py-3"><CardTitle icon={PieChart} title="Composition"/></div><div className="grid grid-cols-[minmax(0,1fr)_70px_110px_120px_70px] gap-3 border-b border-border bg-muted/20 px-4 py-2 text-[8px] font-bold uppercase tracking-wider text-muted-foreground"><span>Instrument</span><span className="text-right">Shares</span><span className="text-right">Total Value (R)</span><span>Weight</span><span className="text-right">Day Chg</span></div><div className="divide-y divide-border px-4">{holdings.map((h,index)=>{const security=sec(h);const symbol=String(h.ticker||h.symbol||"");const shares=Number(h.shares||h.quantity||1);const price=Number(security?.last_price||0)/100;const totalWeight=holdings.reduce((sum,row)=>sum+Number(row.weight||0),0);const weight=totalWeight?Number(h.weight||0)/totalWeight*100:100/Math.max(1,holdings.length);const change=Number(security?.change_percent||0);return <div key={`${symbol}-${index}`} className="grid grid-cols-[minmax(0,1fr)_70px_110px_120px_70px] items-center gap-3 py-3"><div className="flex min-w-0 items-center gap-2"><div className="flex h-8 w-8 shrink-0 items-center justify-center overflow-hidden rounded-full bg-primary/10 text-[8px] font-bold text-primary">{security?.logo_url?<img src={security.logo_url} alt="" className="h-full w-full object-cover"/>:normalize(symbol).slice(0,2)}</div><div className="min-w-0"><p className="text-xs font-bold">{normalize(symbol)}</p><p className="truncate text-[9px] text-muted-foreground">{security?.name||symbol}</p></div></div><span className="text-right font-mono text-[10px]">{shares}</span><span className="text-right font-mono text-[10px] font-bold">{formatZAR(shares*price)}</span><div><div className="flex justify-between font-mono text-[9px]"><span>{weight.toFixed(1)}%</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100,weight)}%`}}/></div></div><span className={cn("text-right font-mono text-[10px] font-bold",change>=0?"text-success":"text-destructive")}>{formatPct(change)}</span></div>})}</div></section>
      <section className="glass-panel col-span-12 overflow-hidden lg:col-span-5"><div className="border-b border-border px-4 py-3"><CardTitle icon={Users} title="Investors"/></div><div className="divide-y divide-border px-4">{data.investors.length?data.investors.map(investor=><div key={investor.userId} className="flex items-center py-3"><span className="min-w-0 flex-1 truncate text-xs font-semibold">{investor.name}</span><span className="font-mono text-[10px]">{formatZAR(investor.value)}</span><span className={cn("ml-3 w-14 text-right font-mono text-[10px] font-bold",(investor.ytd??0)>=0?"text-success":"text-destructive")}>{investor.ytd==null?"—":formatPct(investor.ytd)}</span></div>):<p className="py-8 text-center text-xs text-muted-foreground">No linked investors.</p>}</div></section>
    </div>
  </div>;
}

function SecurityRibbon({holdings,securityFor}:{holdings:Holding[];securityFor:(holding:Holding)=>Sec|undefined}){const rows=holdings.map(holding=>({holding,security:securityFor(holding)}));const doubled=[...rows,...rows];return <div className="-mx-4 -mt-4 overflow-hidden border-y border-border bg-background/35 sm:-mx-6 sm:-mt-6"><div className="strategy-market-ticker flex w-max items-center whitespace-nowrap" style={{animationDuration:`${Math.max(20,rows.length*4)}s`}}>{doubled.map(({holding,security},index)=>{const symbol=String(holding.ticker||holding.symbol||"").replace(/\.JO$/i,"");const price=Number(security?.last_price||0)/100;const change=Number(security?.change_percent||0);return <div key={`${symbol}-${index}`} className="flex h-9 items-center gap-2 border-r border-border px-5"><span className="font-mono text-[10px] font-bold">{symbol}</span><span className="font-mono text-[10px] text-muted-foreground">{price?formatZAR(price):"—"}</span><span className={cn("font-mono text-[10px] font-bold",change>=0?"text-success":"text-destructive")}>{change>=0?"↑":"↓"} {Math.abs(change).toFixed(2)}%</span></div>})}</div></div>}

function ExposureDonut({holdings}:{holdings:Holding[]}){const palette=["#7c3aed","#06b6d4","#10b981","#f59e0b","#ec4899","#6366f1","#ef4444","#84cc16"];const raw=holdings.map((holding,index)=>({symbol:String(holding.ticker||holding.symbol||"").replace(/\.JO$/i,""),value:Number(holding.weight||0),color:palette[index%palette.length]!}));const total=raw.reduce((sum,row)=>sum+row.value,0);const rows=raw.map(row=>({...row,pct:total>0?row.value/total*100:100/Math.max(1,raw.length)}));let cursor=0;const stops=rows.map(row=>{const start=cursor;cursor+=row.pct;return `${row.color} ${start.toFixed(2)}% ${cursor.toFixed(2)}%`;}).join(", ");return <div className="mt-4 flex items-center gap-5"><div className="relative h-36 w-36 shrink-0 rounded-full" style={{background:`conic-gradient(${stops||"hsl(var(--muted)) 0 100%"})`}}><div className="absolute inset-[23%] flex flex-col items-center justify-center rounded-full border border-border bg-card shadow-inner"><span className="font-mono text-lg font-bold">{holdings.length}</span><span className="text-[8px] font-bold uppercase tracking-wider text-muted-foreground">Holdings</span></div></div><div className="min-w-0 flex-1 space-y-2">{rows.map(row=><div key={row.symbol} className="flex items-center gap-2 text-[10px]"><span className="h-2 w-2 shrink-0 rounded-full" style={{background:row.color}}/><span className="min-w-0 flex-1 truncate font-semibold">{row.symbol}</span><span className="font-mono font-bold">{row.pct.toFixed(1)}%</span></div>)}</div></div>}

function CardTitle({icon:Icon,title}:{icon:React.ComponentType<{className?:string}>;title:string}){return <div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="h-3.5 w-3.5"/></span><h2 className="text-xs font-bold">{title}</h2></div>}
function Kpi({label,value}:{label:string;value:string}){return <div className="min-w-24 px-3 py-2 text-center"><p className="text-[8px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-0.5 font-mono text-xs font-bold">{value}</p></div>}
function PerformanceChart({rows}:{rows:ReturnRow[]}){const [period,setPeriod]=React.useState<"1M"|"3M"|"YTD"|"ALL">("YTD");const all=rows.filter(row=>Number(row.basket_value)>0);const end=all.at(-1)?new Date(all.at(-1)!.as_of_date):new Date();const start=new Date(end);if(period==="1M")start.setMonth(start.getMonth()-1);if(period==="3M")start.setMonth(start.getMonth()-3);if(period==="YTD")start.setMonth(0,1);const series=period==="ALL"?all:all.filter(row=>new Date(row.as_of_date)>=start);if(series.length<2)return <p className="flex h-56 items-center justify-center text-xs text-muted-foreground">No performance history available for {period}.</p>;const base=Number(series[0]!.basket_value);const values=series.map(row=>Number(row.basket_value)/base*100);const min=Math.min(...values),max=Math.max(...values),pad=Math.max(1,(max-min)*.15),low=min-pad,high=max+pad,range=high-low;const coords=values.map((value,index)=>({x:(index/(values.length-1))*100,y:90-((value-low)/range)*76,value,date:series[index]!.as_of_date}));const points=coords.map(point=>`${point.x},${point.y}`).join(" ");return <div><div className="mt-2 flex justify-end gap-1">{(["1M","3M","YTD","ALL"] as const).map(item=><button type="button" key={item} onClick={()=>setPeriod(item)} className={cn("rounded-md px-2 py-1 text-[9px] font-bold",period===item?"bg-primary text-primary-foreground":"bg-muted/50 text-muted-foreground")}>{item}</button>)}</div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="mt-1 h-52 w-full overflow-visible"><defs><linearGradient id="perf-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="hsl(var(--primary))" stopOpacity=".28"/><stop offset="1" stopColor="hsl(var(--primary))" stopOpacity="0"/></linearGradient></defs>{[20,55,90].map(y=><line key={y} x1="0" y1={y} x2="100" y2={y} stroke="hsl(var(--border))" strokeWidth=".35" strokeDasharray="2 2"/>)}<polygon points={`0,100 ${points} 100,100`} fill="url(#perf-fill)"/><polyline points={points} fill="none" stroke="hsl(var(--primary))" strokeWidth="1.4" vectorEffect="non-scaling-stroke"/>{coords.filter((_,index)=>index===0||index===coords.length-1).map(point=><circle key={point.date} cx={point.x} cy={point.y} r="1.4" fill="hsl(var(--primary))"><title>{point.date}: {point.value.toFixed(2)}</title></circle>)}</svg><div className="flex justify-between font-mono text-[8px] text-muted-foreground"><span>{series[0]!.as_of_date}</span><span>Indexed to 100 · latest {values.at(-1)!.toFixed(2)}</span><span>{series.at(-1)!.as_of_date}</span></div></div>}
