"use client";

import * as React from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, BarChart3, Newspaper, PieChart, Users } from "lucide-react";
import { cn } from "@/lib/cn";
import { formatPct, formatZAR } from "@/lib/format";

type Holding={symbol?:string;ticker?:string;shares?:number;quantity?:number;weight?:number};
type Strategy={id:string;name:string;short_name?:string;sector?:string;description?:string;holdings?:Holding[];benchmark_name?:string};
type ReturnRow={as_of_date:string;basket_value:number|null;ytd_pct:number|null;all_pct:number|null};
type Sec={symbol:string;name?:string;logo_url?:string;last_price?:number;change_percent?:number};
type Investor={userId:string;name:string;value:number;ytd:number|null};
type Detail={strategy:Strategy;returns:ReturnRow[];securities:Record<string,Sec>;investors:Investor[]};
type News={id:string;source:string;headline:string;body?:string;publishedAt:string};

export default function StrategyOverviewPage(){
  const {id}=useParams<{id:string}>(); const router=useRouter();
  const [data,setData]=React.useState<Detail|null>(null); const [news,setNews]=React.useState<News[]>([]);
  React.useEffect(()=>{void Promise.all([
    fetch(`/api/admin/factsheets?action=detail&id=${encodeURIComponent(id)}`,{cache:"no-store"}).then(r=>r.json()),
    fetch("/api/news?limit=50",{cache:"no-store"}).then(r=>r.json())
  ]).then(([detail,feed])=>{if(detail.ok)setData(detail);setNews(feed.items||[]);});},[id]);
  if(!data)return <div className="py-24 text-center text-sm text-muted-foreground">Loading strategy workspace…</div>;
  const s=data.strategy, holdings=Array.isArray(s.holdings)?s.holdings:[], latest=data.returns.at(-1);
  const normalize=(value:string)=>value.replace(/\.JO$/i,"").toUpperCase();
  const sec=(h:Holding)=>data.securities[String(h.ticker||h.symbol||"")]||data.securities[`${normalize(String(h.ticker||h.symbol||""))}.JO`]||data.securities[normalize(String(h.ticker||h.symbol||""))];
  const minValue=holdings.reduce((sum,h)=>sum+Number(h.shares||h.quantity||1)*(Number(sec(h)?.last_price||0)/100),0);
  const symbols=new Set(holdings.map(h=>normalize(String(h.ticker||h.symbol||""))));
  const relevantNews=news.filter(item=>[...symbols].some(symbol=>item.headline.toUpperCase().includes(symbol))).slice(0,5);
  return <div className="mx-auto max-w-7xl space-y-4 pb-10">
    <button type="button" onClick={()=>router.back()} className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5"/>Back to strategies</button>
    <header className="glass-panel flex flex-wrap items-start gap-4 p-4"><div className="min-w-0 flex-1"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-primary">Strategy overview</p><h1 className="mt-1 text-xl font-bold">{s.name}</h1><p className="text-xs text-muted-foreground">{s.short_name||"MINT"}{s.sector?` · ${s.sector}`:""}</p>{s.description&&<p className="mt-2 max-w-3xl text-xs leading-relaxed text-foreground/70">{s.description}</p>}</div><div className="grid grid-cols-4 divide-x divide-border overflow-hidden rounded-xl border border-border bg-background/30"><Kpi label="Min value" value={minValue?formatZAR(minValue):"—"}/><Kpi label="YTD" value={latest?.ytd_pct!=null?formatPct(Number(latest.ytd_pct)):"—"}/><Kpi label="Holdings" value={String(holdings.length)}/><Kpi label="Investors" value={String(data.investors.length)}/></div></header>
    <div className="grid grid-cols-12 gap-4">
      <section className="glass-panel col-span-12 p-4 lg:col-span-8"><CardTitle icon={BarChart3} title="Performance vs Benchmark"/><PerformanceChart rows={data.returns}/><div className="mt-2 flex justify-end gap-4 text-[9px] text-muted-foreground"><span><i className="mr-1 inline-block h-0.5 w-3 bg-primary"/>Strategy</span><span><i className="mr-1 inline-block h-0.5 w-3 bg-muted-foreground"/>JSE ALSI · benchmark history unavailable</span></div></section>
      <section className="glass-panel col-span-12 p-4 lg:col-span-4"><CardTitle icon={PieChart} title="Sector Exposure"/><div className="mt-4 space-y-2">{holdings.map((h,index)=>{const symbol=normalize(String(h.ticker||h.symbol||""));const total=holdings.reduce((sum,row)=>sum+Number(row.weight||0),0);const weight=total?Number(h.weight||0)/total*100:100/Math.max(1,holdings.length);return <div key={`${symbol}-${index}`}><div className="flex text-[10px]"><span className="font-semibold">{symbol}</span><span className="ml-auto font-mono">{weight.toFixed(1)}%</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${weight}%`}}/></div></div>})}</div></section>
      <section className="glass-panel col-span-12 overflow-hidden lg:col-span-7"><div className="border-b border-border px-4 py-3"><CardTitle icon={PieChart} title="Composition"/></div><div className="divide-y divide-border px-4">{holdings.map((h,index)=>{const security=sec(h);const symbol=String(h.ticker||h.symbol||"");const shares=Number(h.shares||h.quantity||1);const price=Number(security?.last_price||0)/100;return <div key={`${symbol}-${index}`} className="flex items-center gap-3 py-3"><div className="flex h-8 w-8 items-center justify-center overflow-hidden rounded-full bg-primary/10 text-[8px] font-bold text-primary">{security?.logo_url?<img src={security.logo_url} alt="" className="h-full w-full object-cover"/>:normalize(symbol).slice(0,2)}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold">{normalize(symbol)}</p><p className="truncate text-[9px] text-muted-foreground">{security?.name||symbol}</p></div><span className="text-right font-mono text-[10px]">{shares} sh<br/><b>{formatZAR(shares*price)}</b></span><span className={cn("w-14 text-right font-mono text-[10px] font-bold",Number(security?.change_percent||0)>=0?"text-success":"text-destructive")}>{formatPct(Number(security?.change_percent||0))}</span></div>})}</div></section>
      <section className="glass-panel col-span-12 overflow-hidden lg:col-span-5"><div className="border-b border-border px-4 py-3"><CardTitle icon={Users} title="Investors"/></div><div className="divide-y divide-border px-4">{data.investors.length?data.investors.map(investor=><div key={investor.userId} className="flex items-center py-3"><span className="min-w-0 flex-1 truncate text-xs font-semibold">{investor.name}</span><span className="font-mono text-[10px]">{formatZAR(investor.value)}</span><span className={cn("ml-3 w-14 text-right font-mono text-[10px] font-bold",(investor.ytd??0)>=0?"text-success":"text-destructive")}>{investor.ytd==null?"—":formatPct(investor.ytd)}</span></div>):<p className="py-8 text-center text-xs text-muted-foreground">No linked investors.</p>}</div></section>
      <section className="glass-panel col-span-12 overflow-hidden"><div className="border-b border-border px-4 py-3"><CardTitle icon={Newspaper} title="News & Insights"/></div><div className="grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-3">{(relevantNews.length?relevantNews:news.slice(0,6)).map(item=><article key={item.id} className="bg-card p-3"><div className="flex text-[8px]"><span className="font-bold uppercase text-primary">{item.source}</span><span className="ml-auto text-muted-foreground">{new Date(item.publishedAt).toLocaleDateString("en-ZA")}</span></div><p className="mt-1.5 text-[11px] font-semibold leading-snug">{item.headline}</p>{item.body&&<p className="mt-1 line-clamp-2 text-[9px] leading-relaxed text-muted-foreground">{item.body}</p>}</article>)}</div></section>
    </div>
  </div>;
}

function CardTitle({icon:Icon,title}:{icon:React.ComponentType<{className?:string}>;title:string}){return <div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="h-3.5 w-3.5"/></span><h2 className="text-xs font-bold">{title}</h2></div>}
function Kpi({label,value}:{label:string;value:string}){return <div className="min-w-24 px-3 py-2 text-center"><p className="text-[8px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-0.5 font-mono text-xs font-bold">{value}</p></div>}
function PerformanceChart({rows}:{rows:ReturnRow[]}){const series=rows.filter(row=>Number(row.basket_value)>0);if(series.length<2)return <p className="flex h-56 items-center justify-center text-xs text-muted-foreground">No performance history available.</p>;const values=series.map(row=>Number(row.basket_value));const min=Math.min(...values),max=Math.max(...values),range=max-min||1;const points=values.map((value,index)=>`${(index/(values.length-1))*100},${92-((value-min)/range)*80}`).join(" ");return <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="mt-4 h-56 w-full overflow-visible"><defs><linearGradient id="perf-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="hsl(var(--primary))" stopOpacity=".28"/><stop offset="1" stopColor="hsl(var(--primary))" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#perf-fill)"/><polyline points={points} fill="none" stroke="hsl(var(--primary))" strokeWidth="1.4" vectorEffect="non-scaling-stroke"/><line x1="0" y1="92" x2="100" y2="92" stroke="hsl(var(--border))" strokeWidth=".5"/></svg>}
